name: Test against supported Java versions (3.x)

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

env:
  RABBITMQ_IMAGE: 'rabbitmq:3.11'
  DELAYED_MESSAGE_EXCHANGE_PLUGIN_VERSION: 3.11.1

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java: [ '11', '17', '20', '21-ea' ]
    name:  Test against Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v3
      - name: Checkout tls-gen
        uses: actions/checkout@v3
        with:
          repository: rabbitmq/tls-gen
          path: './tls-gen'
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Start RabbitMQ application
        run: ci/start-broker.sh
      - name: Test
        run: |
          ./mvnw verify -Drabbitmqctl.bin=DOCKER:rabbitmq \
            -Dtest-broker.A.nodename=rabbit@$(hostname) \
            -Dtest-tls-certs.dir=tls-gen/basic \
            --no-transfer-progress \
            -Dnet.bytebuddy.experimental=true
      - name: Stop broker
        run: docker stop rabbitmq && docker rm rabbitmq
