name: Build (Linux)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Start RabbitMQ application
        run: bin/start_rabbitmq.sh
      - name: Test
        run: ./mvnw verify -Drabbitmqctl.bin=DOCKER:rabbitmq -Drabbitmq_plugins.bin=DOCKER:rabbitmq
