name: Test against RabbitMQ 3.11 alpha

on:
  schedule:
    - cron: '0 4 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DELAYED_MESSAGE_EXCHANGE_PLUGIN_VERSION: 3.11.1

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        rabbitmq-image: [ 'pivotalrabbitmq/rabbitmq:v3.11.x-otp-max-bazel', 'pivotalrabbitmq/rabbitmq:v3.12.x-otp-max-bazel' ]
    name:  Test against ${{ matrix.rabbitmq-image }}
    steps:
      - uses: actions/checkout@v3
      - name: Checkout tls-gen
        uses: actions/checkout@v3
        with:
          repository: rabbitmq/tls-gen
          path: './tls-gen'
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Start RabbitMQ application
        run: ci/start-broker.sh
      - name: Test
        run: |
          ./mvnw verify -Drabbitmqctl.bin=DOCKER:rabbitmq \
            -Dtest-broker.A.nodename=rabbit@$(hostname) \
            -Dtest-tls-certs.dir=tls-gen/basic \
            --no-transfer-progress
      - name: Stop broker
        run: docker stop rabbitmq && docker rm rabbitmq
